package com.codehive.domain.entity;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;

import java.time.LocalDateTime;

@SuperBuilder
@Getter
@Setter
@NoArgsConstructor
public class Entity {
    /**
     * The difference between using Integer and int is:
     * Integer can be null because before creating entity in database
     * their id is generally null and automatically generated by database
     */
    private Integer id;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
